---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: debian-7.4

suites:
  - name: firewall-ex
    run_list:
      - recipe[apt::default]
      - recipe[fake::default]
    attributes:
      firewall-ex:
        postrouting_rules: [
          '-s 10.10.10.11 -j MASQUERADE'
        ]
        forward_rules: [
          '-m state -s 10.10.10.11 --state RELATED,ESTABLISHED -j ACCEPT'
        ]
